package main

import (
	"errors"
	"net/http"

	"github.com/djudju12/greenlight/internal/data"
	"github.com/djudju12/greenlight/internal/validator"
)

func (app *application) registerUserHandle(w http.ResponseWriter, r *http.Request) {
	var input struct {
		Name     string `json:"name"`
		Email    string `json:"email"`
		Password string `json:"password"`
	}

	err := app.readJSON(w, r, &input)
	if err != nil {
		app.badRequestResponse(w, r, err)
		return
	}

	user := &data.User{
		Name:      input.Name,
		Email:     input.Email,
		Activated: true,
	}

	v := validator.New()
	if data.ValidatePasswordPlaintext(v, input.Password); !v.Valid() {
		app.failedValidationResponse(w, r, v.Errors)
		return
	}

	err = user.Password.Set(input.Password)
	if err != nil {
		app.serverErrorResponse(w, r, err)
		return
	}

	if data.ValidateUser(v, user); !v.Valid() {
		app.failedValidationResponse(w, r, v.Errors)
		return
	}

	err = app.models.Users.Insert(user)
	if err != nil {
		switch {
		case errors.Is(err, data.ErrDuplicateEmail):
			v.AddError("email", "a user with this email address already exists")
			app.failedValidationResponse(w, r, v.Errors)
		default:
			app.serverErrorResponse(w, r, err)
		}

		return
	}

	go func() {
		// i think its important to declare a new error variable with :=
		// because you can have race conditions with the outer scope
		err := app.mailer.Send(user.Email, "user_welcome.go.tmpl", user)
		if err != nil {
			app.logger.PrintError(err, nil)
			return
		}
	}()

	err = app.writeJSON(w, http.StatusCreated, envelope{"user": user}, nil)
	if err != nil {
		app.serverErrorResponse(w, r, err)
	}
}
